### ISSUE TITLE
Exception cause is not logged

### ISSUE THREAD

**Issue by vivekkothari** [newrelic/java-log-extensions#54]
In the following code snippet, we log the exception which is mapped to `error.stack` field,
but if the exception has a cause, it is not logged.

https://github.com/newrelic/java-log-extensions/blob/main/logback/src/main/java/com/newrelic/logging/logback/NewRelicJsonLayout.java#L83-L95

Can we either map it in same field, or a different field?
It can configured using a config if needed.
Also, then the question then remains how far deep we should look for the cause?

If I get some clarity, I can raise a PR.

(Migrate to Jira)

**Comment by kford-newrelic** [comment]
@vivekkothari can you clarify what behavior you experience now (maybe, what you see in NR1?) .vs what you ideally would want to happen?

PR submissions are always welcome!

**Comment by vivekkothari** [comment]
So say I have an exception trace which looks like,

```
Trace of exception1
...

Caused by exception2
Trace of cause of exception1
...

Cause by exception2
```

In NR1 I only see trace of the topmost exception's trace. We don't walk through the causal chain.

**Comment by swanderson1** [comment]
We are having the same issue with the missing  caused by sections.

The code could just use ch.qos.logback.classic.spi.ThrowableProxyUtil.asString. For example, the code inside NewRelicJsonLayout.writeToGenerator for the stack.trace element would be
```
    IThrowableProxy proxy = event.getThrowableProxy();
    if (proxy != null) {
      generator.writeObjectField(ElementName.ERROR_CLASS, proxy.getClassName());
      generator.writeObjectField(ElementName.ERROR_MESSAGE, proxy.getMessage());
      generator.writeObjectField(ElementName.ERROR_STACK, ThrowableProxyUtil.asString(proxy));
    }

    generator.writeEndObject();
```

The stack trace size enforcement adds a question on where the limit would be applied with the caused by. I think sticking with the standard java stack trace format is best or at least disabling the size enforcement.

**Comment by kford-newrelic** [comment]
Will add this to the agent roadmap. Trying to target the Oct-Dec quarter.

**Comment by vivekkothari** [comment]
Any update on this?

**Comment by kford-newrelic** [comment]
@vivekkothari we tried to carve out bandwidth to tackle this issue in prior quarters but were not able to. We do not have anything planned for this at the moment.

**Comment by jlopezinc** [comment]
> We are having the same issue with the missing caused by sections.
> 
> The code could just use ch.qos.logback.classic.spi.ThrowableProxyUtil.asString. For example, the code inside NewRelicJsonLayout.writeToGenerator for the stack.trace element would be
> 
> ```
>     IThrowableProxy proxy = event.getThrowableProxy();
>     if (proxy != null) {
>       generator.writeObjectField(ElementName.ERROR_CLASS, proxy.getClassName());
>       generator.writeObjectField(ElementName.ERROR_MESSAGE, proxy.getMessage());
>       generator.writeObjectField(ElementName.ERROR_STACK, ThrowableProxyUtil.asString(proxy));
>     }
> 
>     generator.writeEndObject();
> ```
> 
> The stack trace size enforcement adds a question on where the limit would be applied with the caused by. I think sticking with the standard java stack trace format is best or at least disabling the size enforcement.

This @swanderson1 comment looks like a good solution. Logback does a good job of generating a human-readable stack trace will all the necessary information, so why mess with it and reinvent the wheel?

Trimming the stack trace (configurable since https://github.com/newrelic/java-log-extensions/pull/75) looks dangerous for debugging production issues in real-life scenarios. In our case, we found out that stack traces without "caused by"/nested exceptions are pretty much useless.

I agree that at the very least there should be an opt-in configuration to properly log the full stack trace with `ThrowableProxyUtil`.

**Comment by jlopezinc** [comment]
Following my previous comment I propose a solution on https://github.com/newrelic/java-log-extensions/pull/78

**Comment by lcalisi** [comment]
We discovered this behavior over the weekend and reverted the new relic log format. Looking inner stack traces is more important  to us vs the benefits the custom appender provides.

**Comment by vivekkothari** [comment]
> We discovered this behavior over the weekend and reverted the new relic log format. Looking inner stack traces is more important  to us vs the benefits the custom appender provides. 

@lcalisi i tried ingesting logs without the newrelic encoder but found that newrelic doesn't show the logs. Could you pls help with a sample log back config which works for you without this custom appender/encoder?

**Comment by obenkenobi** [comment]
While [#78])(https://github.com/newrelic/java-log-extensions/pull/78) does get the full stack trace, ideally what we would like is for us to be able to show the exception cause while within the stack trace while also providing us with the option to show the full stack trace at the customer's own risk.
