### ISSUE TITLE
Kotlin transitive dependency from OKhttp causes conflicts with apps using later Kotlin versions

### ISSUE THREAD

**Issue by tbradellis** [newrelic/java-log-extensions#56]
[recent update](https://github.com/newrelic/java-log-extensions/pull/55) to logback:2.4.0 on April 6 is causing runtime issues in their Spring Boot GraphQL applications. They noticed version 2.4.0 has some built-in Kotlin collection classes that seem to be older and are in conflict with other Kotlin dependencies at version 1.5.32 that they are using.

Internally, there are more details here:
https://newrelic.atlassian.net/browse/GTSE-14337

(migrate to Jira)

**Comment by meiao** [comment]
The Kotlin dependencies are brought transitively from `com.newrelic.logging:forwarder`, which depends on `com.newrelic.telemetry:telemetry-http-okhttp` which depends on OkHttp which has the Kotlin dependencies.

Currently there is not easy workaround since the dependencies from `forwarder` are included in the com.newrelic.logging:logback:2.4.0 jar.

Since `com.newrelic.logging:logback` is usually a compile/build time dependency, we could remove the dependencies from inside the jar and let Maven or Gradle take care of getting the dependencies. If we do that, anyone experiencing this problem could exclude the `com.newrelic.telemetry:telemetry-http-okhttp` and bring in `com.newrelic.telemetry:telemetry-http-java11` instead (as long as they are using Java 11).

In this case, the Maven configuration would look like:

```
<dependency>
  <groupId>com.newrelic.logging</groupId>
  <artifactId>logback</artifactId>
  <version>2.4.0</version>
  <exclusions>
    <exclusion>
      <dependency>
        <groupId>com.newrelic.telemetry</groupId>
        <artifactId>telemetry-http-okhttp</artifactId>
      </dependency>
    </exclusion>
  </exclusions>
</dependency>
<dependency>
  <groupId>com.newrelic.telemetry</groupId>
  <artifactId>telemetry-http-java11</artifactId>
  <version>0.13.1</version>
</dependency>
```

And Gradle:
```
implementation('com.newrelic.logging:logback:2.4.0') {
  exclude(group: implementation 'com.newrelic.telemetry', module: 'telemetry-http-okhttp'
}
implementation 'com.newrelic.telemetry:telemetry-http-java11:0.13.1'
```
